Metrist-Software/orchestrator

.github/workflows/main.yaml
Needed to prevent silently updating the erlang version and getting and 'old PLT' error when using cached PLT. Already added to action in backend repo
=> Set erlef/setup-beam@v1 action to use version-type strict option

lib/orchestrator/config_fetcher.ex, lib/orchestrator/configuration.ex, lib/orchestrator/monitor_supervisor.ex, test/orchestrator/configuration_test.exs
While digging into roll-out issues, it looked like configuration changes weren't propagating; we had to unschedule and reschedule monitors. 
The code looks good though, but a critical log statement is missing to be sure the next time around. Therefore, added logging; also renamed a method to make it more clear what it was doing, added some docs, and a test specific to the kind of config change that was made when the issues appeared.
=> Cleanups and extra tests for config change handling

lib/orchestrator/configuration.ex, test/orchestrator/configuration_test.exs
If extra_config was null, `protocol Enumerable not implemented for nil of type Atom` would be thrown as it tried to run Enum.map against nil
=> Allow for null extra_config

orchestrator.yaml
We're still running Orchestrator on CloudFormation although we're moving away from that. This PR cleans the template as much as possible so that we know what the new run method (on straight EC2) requires as configuration.
[internal ticket MET-323]
=> Cleanup CloudFormation template

lib/orchestrator/protocol_handler.ex, test/orchestrator/protocol_handler_test.exs
Use the byte_size/0 to calculate the message's byte size. 
**Deployment**
See related PR
=> Using byte_size instead of String.length in the protocol

INSTALL.md
This gives you a 404 https://github.com/Metrist-Software/orchestrator/main/dist/trustedkeys.gpg
```sh
wget -nc https://github.com/Metrist-Software/orchestrator/main/dist/trustedkeys.gpg
--2022-10-04 13:35:55--  https://github.com/Metrist-Software/orchestrator/main/dist/trustedkeys.gpg
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-04 13:35:56 ERROR 404: Not Found.
```
This doesnt https://github.com/Metrist-Software/orchestrator/blob/main/dist/trustedkeys.gpg
=> Use the correct path to trustedkeys.gpg

Makefile, lib/orchestrator/dotnet_dll_invoker.ex, lib/orchestrator/executable_invoker.ex, lib/orchestrator/invoker.ex
This ensures that we only have a single place to download (until now, downloads are done inside the .NET wrapper code). We will now always pass the path argument to the DLL wrapper code whether we run in test mode or not.
Internal ticket MET-672.
=> Have .NET invoker also do a download first.

lib/orchestrator/aws_secrets_manager.ex
Just a simple fix. We reuse the RDS connection string secret for our instance of the AWS RDS "persistent" monitor, and that one has a numeric port. The protocol sends strings over, and other places expect strings, so it makes sense to just cast to string here.
Metrist ticket MET-1034
=> Force AWS secrets to be returned as strings

lib/orchestrator/monitor_scheduler.ex
This prevents us from logging "Unknown message received" on every normal monitor process exit.
=> Handle normal exit message

lib/orchestrator/ipa_server.ex, lib/orchestrator/protocol_handler.ex
This helps us figure out telemetry source indicators in the web UI.
=> MET-1049 Tag metrics/errors so we know the source of telemetry data

lib/orchestrator/protocol_handler.ex
Looks like the ProtocolHandler genserver processes weren't being stopped when a monitor didn't exit gracefully (specifically with an "Exit" message sent from it). We're already force killing the actual os monitor processes here to be safe, so this does the same for the genserver processes.
Currently running in dev, but it's slow to actually have the memory grow since it needs the monitor run to error
=> MET-1102 Orchestrator memory leak

dist/amazon-linux/2/Dockerfile, dist/ubuntu/20.04/Dockerfile, dist/ubuntu/22.04/Dockerfile, lib/mix/tasks/metrist/run_monitor.ex
Adds .cache dir to base images which is required for erlexec compilation. (Tested with a local built docker container of 20.04)
Also ensures erlexec is available in run_monitor
Deployment
Merge
Note: All dist base images have already been rebuilt and pushed
=> Hotfix dist builds erlexec

dist/amazon-linux/2/Dockerfile, dist/ubuntu/20.04/Dockerfile, dist/ubuntu/22.04/Dockerfile, lib/mix/tasks/metrist/run_monitor.ex
Reverting because monitors are getting into perpetual overtime after a successful completion occasionally. Will look again on Monday.
Reverts Metrist-Software/orchestrator#147
=> Revert "Hotfix dist builds erlexec"

lib/mix/tasks/metrist/run_monitor.ex
The new invokers require a `Task.Supervisor` with name `Orchestrator.TaskSupervisor` to function. This updates the mix task to start one.
=> Ensure run_monitor has the req task supervisor

.github/workflows/dist-e2e.yml, dist/amazon-linux/2/Vagrantfile, dist/e2e.sh, dist/interactive/install.sh, dist/ubuntu/20.04/Vagrantfile, dist/ubuntu/22.04/Vagrantfile
Adds vagrant based e2e tests that run every day at 17:00 UTC via github actions.
1. Provisions the vagrant VM (done every time to ensure we have the latest packages)
2. Installs Orchestrator via our interactive install.sh script
3. Runs testsignal (dotnet DLL monitor) within 30s
4. Checks to ensure testsignal existed properly
5. Uninstalls/purges and stops the Orchestrator
6. Destroys the vagrant VM (clean slate next run)
Account that this sends telemetry to is `Orchestrator dist e2e`
There's a hard 30m timeout on the e2e job in case a parallel run gets stuck somehow (I have seen provisioning of the vagrant VM take 2m or 7m as an example on the same vagrant box)
Uses `macos-12` Github Action runner image as that is the only image that supports nested virtualization at the moment. Request …
=> Add e2e distribution tests

config/dev.exs, config/runtime.exs, lib/orchestrator/application.ex, lib/orchestrator/monitor_running_alerting.ex, lib/orchestrator/monitor_scheduler.ex, test/orchestrator/monitor_running_alerting_test.exs
Adds a genserver that tracks recent activity for monitors, hooked into the scheduler. Will send a POST to a configured webhook endpoint if no activity measured for > 5 minutes
=> MET-1159 Monitor/Instance not running alerting

.github/workflows/dist-e2e.yml, .github/workflows/main.yaml, dist/do-build.sh, dist/interactive/install.sh, dist/rhel/7/Dockerfile, dist/rhel/7/Vagrantfile, dist/rhel/7/after-remove.sh, dist/rhel/7/fpm.cmd, dist/rhel/7/inc/etc/default/metrist-orchestrator, dist/rhel/7/inc/etc/systemd/system/metrist-orchestrator.service
Enables rhel7 in the install script and adds building + e2e testing. Uses CentOS 7 docker image to build the rpm due to issues authenticating the subscription on docker, which was required to install certain dev packages
=> MET-1183 Add support for RedHat 7.9 to interactive install script

lib/orchestrator/invoker.ex, lib/orchestrator/monitor_running_alerting.ex
Triggered by orphaned chromium processes from the New Relic ui checks, this will make the orchestrator spawn monitor processes in their own groups which, with the `:kill_group` option, will ensure the entire group is killed once the main process exits.
=> MET-1192 Ensure all processes related to a monitor run are cleaned up

lib/orchestrator/application.ex, lib/orchestrator/config_fetcher.ex, lib/orchestrator/configuration.ex, lib/orchestrator/invoker.ex, lib/orchestrator/monitor_scheduler.ex, lib/orchestrator/monitor_supervisor.ex
So that changes from for example AWS Secrets Manager propagate without requiring restarts.
After starting adding refresh, decided to drop caching instead. Extra cost is negligible and this propagates secrets changes the fastest way possible.
PR also includes some assorted minor cleanups of the code.
=> MET-1194 Make orchestrator refresh configs

.github/workflows/main.yaml, dist/build.sh, dist/invalidate_cloudfront.sh
This avoids errors from CloudFront when invalidate actions are called too often.
=> MET-1212 Only invalidate CloudFront once

.github/workflows/main.yaml, dist/invalidate_cloudfront.sh
We no longer have $dist so can't use that in the cloudfront invalidation and since deploy.sh also writes latest.txt files to dist we should wait for that to be complete as well before invalidating (both write to a folder under orchestrator/*)
Tested on dev
=> Hotfix cloudfront invalidation on build

lib/orchestrator/application.ex, lib/orchestrator/invoker.ex, lib/orchestrator/metrist_api.ex, lib/orchestrator/monitor_running_alerting.ex, lib/orchestrator/slack_reporter.ex
WISOTT. 
Tested with `tcpdump host 54.186.126.55 or host 54.203.73.8` running to keep an eye on traffic to app.metrist.io and with Squid on a different box, with and without the proxy variables, and it operated as expected.
=> Ensure we honour proxy environment variables

build-and-push.sh, dist/build-base.sh, dist/build.sh, dist/e2e.sh
The last orchestrator deploy was using the -preview tag because it looking at the `master` branch. This PR changes to look for `main` branch and increases the timeout for e2e test
=> Use main for GITHUB_REF

dist/rocky/8/Vagrantfile, dist/rocky/8/fpm.cmd
The dll runner was getting this error because `libicu` was not installed in rocky
```
[vagrant@localhost ~]$ /tmp/.metrist-bwcache/F258B0A731C33248C1875535400C9A57F9553C8C/lib/orchestrator-0.1.0/priv/runner/Metrist.Runner testsignal /root/.cache/metrist/monitors/testsignal
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
at System.Environment.FailFast(System.String)
at System.Globalization.GlobalizationMode+Settings..cctor()
at System.Globalization.CultureData.CreateCultureWithInvariantData() …
```
=> Add libicu to deps

lib/mix/tasks/metrist/run_monitor.ex, lib/orchestrator/configuration.ex, lib/orchestrator/dotnet_dll_invoker.ex, lib/orchestrator/executable_invoker.ex, lib/orchestrator/monitor_scheduler.ex, lib/orchestrator/monitor_supervisor.ex, lib/orchestrator/nil_invoker.ex, lib/orchestrator/ping_invoker.ex, test/orchestrator/ping_invoker_test.exs
Nice test to see how flexible the monitor invocation framework is in Orchestrator, the Ping monitor is built-in so it becomes a very cheap way to do basic checks against a bunch of endpoints.
Note that a lot of sites block ICMP. If this is deemed useful, we probably want to extend this to SYN checking (making an actual connection). 
New monitor:
Addition to existing monitor:
Blocked API (don't do this in production ;-)):
=> MET-1280 built-in ping monitor

lib/orchestrator/invoker.ex
Caching was working for exe monitors, but not dll monitors due to not having a singular `<monitor_logical_name>` file as part of the distributable. A little awkward since the dist names for dll monitors don't match the logical name (they include `Metrist.Monitors.` and have different capitalization) so instead we just check if there's any `.dll` file available in the cache directory
=> MET-1337 Orchestrator Monitor Caching isn't working
